version: '3'

services:
  app:
    ports:
      - 3000:3000
    build: ./
    command: yarn landing:dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
